### ISSUE TITLE
Support Android API list

### ISSUE THREAD

**Issue by Barney-Steven** [NexaAI/octopus-v4#7]
Hi, fantastic job! When can you publish the Android API implementations for your demos, and  training data ? thanks.

**Comment by zhiyuan8** [comment]
Thanks for the question. Our octopus-V2 has one checkpoint for Android API, while Octopus-V4 (this repo) is a graph of LLMs, not for Android usage specifically.

To test, please see:
https://huggingface.co/NexaAIDev/Octopus-v2
